name: tec
description: this is techblog project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  validators: ^3.0.0
  email_validator: ^3.0.0
  audio_video_progress_bar: ^2.0.3
  get_storage: ^2.1.1
  zoom_tap_animation: ^1.1.0
  html_editor_enhanced: ^2.7.1
  dio: ^5.9.0
  url_launcher: ^6.3.2
  flutter_widget_from_html: ^0.17.1
  numberpicker: ^2.1.2
  share_plus: ^12.0.1
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    


  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: dana
      fonts:
        - asset: assets/fonts/DANA-BOLD.ttf
          weight: 700
        - asset: assets/fonts/DANA-REGULAR.ttf
          weight: 300